input {
  beats {
    port => 5044
  }
}

filter {
  if ![request_id] {
    mutate { add_tag => ["missing_request_id"] }
  }
  mutate {
    remove_field => ["agent", "ecs", "host", "input", "log"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    ilm_enabled => true
    ilm_rollover_alias => "industry-research-logs"
    ilm_pattern => "000001"
    ilm_policy => "industry-research-logs-30d"
  }
}
